#ifndef __KEYCODES_HPP__
#define __KEYCODES_HPP__
#ifdef _WIN32
#pragma once
#endif

#include "common.hpp"
#include <SDL3/SDL.h>

namespace PopLib
{

enum KeyCode
{
	KEYCODE_UNKNOWN,
	KEYCODE_CANCEL,
	KEYCODE_BACK,
	KEYCODE_TAB,
	KEYCODE_CLEAR,
	KEYCODE_RETURN,
	KEYCODE_SHIFT,
	KEYCODE_CONTROL,
	KEYCODE_MENU,
	KEYCODE_PAUSE,
	KEYCODE_CAPITAL,
	KEYCODE_KANA,
	KEYCODE_HANGEUL,
	KEYCODE_HANGUL,
	KEYCODE_JUNJA ,
	KEYCODE_FINAL,
	KEYCODE_HANJA,
	KEYCODE_KANJI,
	KEYCODE_ESCAPE,
	KEYCODE_CONVERT,
	KEYCODE_NONCONVERT,
	KEYCODE_ACCEPT,
	KEYCODE_MODECHANGE,
	KEYCODE_SPACE,
	KEYCODE_PAGEUP,
	KEYCODE_PAGEDOWN,
	KEYCODE_END,
	KEYCODE_HOME,
	KEYCODE_LEFT,
	KEYCODE_UP,
	KEYCODE_RIGHT,
	KEYCODE_DOWN,
	KEYCODE_SELECT,
	KEYCODE_EXECUTE,
	KEYCODE_SNAPSHOT,
	KEYCODE_INSERT,
	KEYCODE_DELETE,
	KEYCODE_HELP,
	KEYCODE_ASCIIBEGIN = 0x30,
	KEYCODE_ASCIIEND = 0x7a,
	KEYCODE_LWIN,
	KEYCODE_RWIN,
	KEYCODE_APPS,
	KEYCODE_NUMPAD0,
	KEYCODE_NUMPAD1,
	KEYCODE_NUMPAD2,
	KEYCODE_NUMPAD3,
	KEYCODE_NUMPAD4,
	KEYCODE_NUMPAD5,
	KEYCODE_NUMPAD6,
	KEYCODE_NUMPAD7,
	KEYCODE_NUMPAD8,
	KEYCODE_NUMPAD9,
	KEYCODE_MULTIPLY,
	KEYCODE_ADD,
	KEYCODE_SEPARATOR,
	KEYCODE_SUBTRACT,
	KEYCODE_DECIMAL,
	KEYCODE_DIVIDE,
	KEYCODE_F1,
	KEYCODE_F2,
	KEYCODE_F3,
	KEYCODE_F4,
	KEYCODE_F5,
	KEYCODE_F6,
	KEYCODE_F7,
	KEYCODE_F8,
	KEYCODE_F9,
	KEYCODE_F10,
	KEYCODE_F11,
	KEYCODE_F12,
	KEYCODE_F13,
	KEYCODE_F14,
	KEYCODE_F15,
	KEYCODE_F16,
	KEYCODE_F17,
	KEYCODE_F18,
	KEYCODE_F19,
	KEYCODE_F20,
	KEYCODE_F21,
	KEYCODE_F22,
	KEYCODE_F23,
	KEYCODE_F24,
	KEYCODE_NUMLOCK,
	KEYCODE_SCROLL,
};

KeyCode GetKeyCodeFromName(const std::string &theKeyName);
KeyCode GetKeyCodeFromSDLKeycode(const SDL_Keycode key);
const std::string GetKeyNameFromCode(const KeyCode &theKeyCode);

} // namespace PopLib

#endif